name: Deploy Angular Frontend

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      TERRAFORM_CLI_PATH: /home/runner/work/_temp/*

    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.8.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

          id: outputs
          run: |
            echo "ecr_repository_url=$(terraform output -raw ecr_repository_url)" >> $GITHUB_ENV
            echo "ecs_cluster_name=$(terraform output -raw ecs_cluster_name)" >> $GITHUB_ENV
            echo "ecs_service_name=$(terraform output -raw ecs_service_name)" >> $GITHUB_ENV
    
      - name: Use Terraform Outputs
        run: |
            echo "ECR Repository URL: ${{ env.ecr_repository_url }}"
            echo "ECS Cluster Name: ${{ env.ecs_cluster_name }}"
            echo "ECS Service Name: ${{ env.ecs_service_name }}"
    
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Build, Tag, and Push Docker Image
        run: |
          docker build -t ${{ needs.terraform.outputs.ecr_repository_url }}:latest .
          docker push ${{ needs.terraform.outputs.ecr_repository_url }}:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Update ECS Service
        run: |
          aws ecs update-service --cluster ${{ needs.terraform.outputs.ecs_cluster_name }} --service ${{ needs.terraform.outputs.ecs_service_name }} --force-new-deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
